detectors:
  DuplicateMethodCall:
    enabled: false
  IrresponsibleModule:
    enabled: false
  TooManyConstants:
    enabled: false
  UncommunicativeMethodName:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  UncommunicativeParameterName:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UnusedPrivateMethod:
    enabled: false
  UtilityFunction:
    public_methods_only: true
exclude_paths:
  - lib/legacy
  - lib/rake/legacy_tasks
  - lib/smelly.rb
