# New cops
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Miscelleneous
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Auto-correct
Layout/DefEndAlignment:
  AutoCorrect: true
Layout/EndAlignment:
  AutoCorrect: true
Layout/LineLength:
  Enabled: true
  AutoCorrect: true

# Indentation
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Line breaks
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

# Trailing commas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Disable annoyances
Metrics:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericPredicate:
  Enabled: false

# Class structure
Layout/ClassStructure:
  Enabled: true
  AutoCorrect: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - attr_accessor
    - attr_reader
    - attr_writer
    - delegate
    - public_class_methods
    - initializer
    - public_methods
    - protected_class_methods
    - protected_methods
    - private_class_methods
    - private_methods
